Test class/rub 191 196
crmmetry/JNGroupProject pull request #143
Opened 2021-03-02 18:33 UTC by sunilspatil

Hello @RemarioCRM 
Please see the required test class files

2021-03-03 18:16 UTC, RemarioCRM requested changes

2021-03-03 18:16 UTC, RemarioCRM commented on force-app/main/default/classes/ContentDocTriggerHandler.cls
> +    public static void CheckIfAllDocumentsAreUploaded(list<ContentDocument> contenDocsList){
@sunilspatil not seeing the latest changes for preassessment checkbox

2021-03-03 18:17 UTC, RemarioCRM commented on force-app/main/default/classes/ContentDocTriggerHandler.cls
> +    public static void CheckIfAllDocumentsAreUploaded(list<ContentDocument> contenDocsList){
merge with the release branch then push again

2021-03-04 13:52 UTC, sunilspatil commented on force-app/main/default/classes/ContentDocTriggerHandler.cls
> +    public static void CheckIfAllDocumentsAreUploaded(list<ContentDocument> contenDocsList){
ok

2021-03-05 06:26 UTC, sunilspatil commented
Hello @RemarioCRM 
I think we can ignore this branch as below files are already committed and merged with Rub 229.
      force-app/main/default/classes/ContentDocTriggerHandler.cls
      force-app/main/default/classes/ContentDocTriggerHandler.cls-meta.xml

And below file is already committed and merged when I created PR for PDF changes
      force-app/main/default/classes/CreditApplicationSummaryDocument.cls

Now only question remained is for the below file. I will create a new branch for this TestDataFactory.cls file and create PR.
     force-app/main/default/classes/TestDataFactory.cls

 

cc: @ishwari

2021-03-05 06:27 UTC, closed without merging