Feature/rub 420
crmmetry/JNGroupProject pull request #190
Opened 2021-04-16 15:56 UTC by TusharChopade

2021-04-19 12:21 UTC, RemarioCRM requested changes

2021-04-19 12:21 UTC, RemarioCRM commented on force-app/main/default/classes/TestApplicationTriggerHandler.cls
> +  @isTest
what is the current code coverage

2021-04-20 05:23 UTC, TusharChopade commented on force-app/main/default/classes/TestApplicationTriggerHandler.cls
> +  @isTest
Current code coverage in 100%

2021-04-20 05:24 UTC, TusharChopade commented on force-app/main/default/classes/ApplicationTriggerHandler.cls
> +  public static void checkOpportunityHasOneAppliaction() {
i have added jsdocs comments and pushed back to git. please check

2021-04-21 21:01 UTC, merged