In Progress Implmentation for SkillsBasedRouting modification
crmmetry/JNGroupProject pull request #199
Opened 2021-04-21 14:50 UTC by CRMTravis

2021-04-21 15:34 UTC, RemarioCRM requested changes

2021-04-21 15:34 UTC, RemarioCRM commented on force-app/main/default/classes/SkillsBasedRouting.cls
> +        for (String product : serviceResourceProductSkillNames) {
serviceResourceLoactionSkillNames and serviceResourceProductSkillNames need to be related by their UserId to work, consider multiple users.

2021-04-21 17:44 UTC, RemarioCRM requested changes

2021-04-21 17:44 UTC, RemarioCRM commented on force-app/main/default/classes/ServiceResourceWrapper.cls
> +public with sharing class ServiceResourceWrapper {
This should be an inner class

2021-04-21 18:01 UTC, CRMTravis commented on force-app/main/default/classes/ServiceResourceWrapper.cls
> +public with sharing class ServiceResourceWrapper {
Why exactly?

2021-04-22 15:37 UTC, RemarioCRM requested changes

2021-04-24 13:22 UTC, RemarioCRM requested changes

2021-04-24 13:22 UTC, RemarioCRM commented on force-app/main/default/classes/TestSkillsBasedRouting.cls
> +
Remove all dead commented code

2021-04-24 13:22 UTC, RemarioCRM commented on force-app/main/default/classes/SkillsBasedRouting.cls
> +              .addProduct(skillRecord.Skill.MasterLabel);
For all the grouped queries , ADD with security enforced

2021-04-24 13:22 UTC, RemarioCRM commented on force-app/main/default/classes/SkillsBasedRouting.cls
> +              .addProduct(skillRecord.Skill.MasterLabel);
ensure the claass uses with sharing

2021-04-24 13:22 UTC, RemarioCRM commented on force-app/main/default/classes/TestSkillsBasedRouting.cls
>        newLead[0].Last_Contact_Made__c = System.now();
great job, but im not seeing no negative test scenario when the user does not the matching location or product.

2021-04-24 21:02 UTC, RemarioCRM approved these changes

2021-04-24 21:02 UTC, merged