VF page for Ticket
crmmetry/JNGroupProject pull request #202
Opened 2021-04-23 11:49 UTC by ishwari-gaikwad2

2021-04-23 14:11 UTC, RemarioCRM requested changes

2021-04-23 14:11 UTC, RemarioCRM commented on force-app/main/default/pages/AutoCreditScoreModel.page
> +            J-LODM-703-F83- Ver 2-September 23, 2020
why is this hardcoded ?, this should be current date

2021-04-26 13:09 UTC, RemarioCRM commented on force-app/main/default/pages/AutoCreditScoreModel.page
> +            J-LODM-703-F83- Ver 2-September 23, 2020
is this done?

2021-04-26 14:16 UTC, ishwari-gaikwad2 commented on force-app/main/default/pages/AutoCreditScoreModel.page
> +            J-LODM-703-F83- Ver 2-September 23, 2020
yes and changes are pushed to git hub

2021-04-26 15:53 UTC, RemarioCRM approved these changes

2021-04-26 15:53 UTC, merged