process builder changes
crmmetry/JNGroupProject pull request #215
Opened 2021-04-27 15:10 UTC by TusharChopade

2021-04-27 16:27 UTC, RemarioCRM commented
@TusharChopade please push the Flow not FlowDefinition files.

2021-04-27 16:27 UTC, RemarioCRM requested changes

2021-04-27 16:27 UTC, RemarioCRM commented on force-app/main/default/flowDefinitions/Rubicon_Path_Automation.flowDefinition-meta.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
Push flow not flowdefinition

2021-04-28 05:23 UTC, TusharChopade commented on force-app/main/default/flowDefinitions/Rubicon_Path_Automation.flowDefinition-meta.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
Hi , i have pushed flow here instead of flowdefinition

2021-04-29 15:10 UTC, merged