These are some changes from RUB-290
crmmetry/JNGroupProject pull request #230
Opened 2021-05-18 13:58 UTC by ishwari-gaikwad2

2021-05-19 20:18 UTC, RemarioCRM requested changes

2021-05-19 20:18 UTC, RemarioCRM commented on force-app/main/default/classes/CaseTriggerHandler_Test.cls
> +    if (applicationList.size() > 0) {
Please USE Constants in Constants.Cls file in all Tests

2021-05-19 20:19 UTC, RemarioCRM requested changes

2021-05-19 20:19 UTC, RemarioCRM commented on force-app/main/default/classes/CaseTriggerHandler.cls
> +      WHERE Status = 'Active' AND Name = :''
i dont understand this query AND Name = :'', Does the Entitlement not have a name?

2021-05-20 04:15 UTC, ishwari-gaikwad2 commented on force-app/main/default/classes/CaseTriggerHandler.cls
> +      WHERE Status = 'Active' AND Name = :''
I need to push this file again I have made changes to it. I have added the name in constants and then used that in condition.

2021-05-20 04:16 UTC, ishwari-gaikwad2 commented on force-app/main/default/classes/CaseTriggerHandler_Test.cls
> +    if (applicationList.size() > 0) {
sure i will use constants in test class as well

2021-05-20 21:49 UTC, merged