Apex for RUB-214
crmmetry/JNGroupProject pull request #232
Opened 2021-05-18 14:09 UTC by ishwari-gaikwad2

2021-05-18 16:22 UTC, RemarioCRM requested changes

2021-05-18 16:22 UTC, RemarioCRM commented on force-app/main/default/classes/ApplicationTriggerHandler.cls
> +  private static Map<String, Group> getQueueMap() {
use this getQueueId from Util class instead

2021-05-18 16:22 UTC, RemarioCRM commented on force-app/main/default/classes/ApplicationTriggerHandler.cls
> +    Map<String, Group> groupMap = getQueueMap();
use getQueueId from Util

2021-05-19 20:11 UTC, RemarioCRM requested changes

2021-05-19 20:11 UTC, RemarioCRM commented on force-app/main/default/triggers/ApplicationTrigger.trigger
> +    if (Trigger.isBefore) {
why did you change this @ishwari-gaikwad2

2021-05-20 04:19 UTC, ishwari-gaikwad2 commented on force-app/main/default/triggers/ApplicationTrigger.trigger
> +    if (Trigger.isBefore) {
We have validation on application creation that opportunity will not have more than 2 applications. but that was not working as that trigger was on after insert. so I have changed it.

2021-05-25 21:07 UTC, RemarioCRM requested changes

2021-05-25 21:07 UTC, RemarioCRM commented
merge and resolve all conflicts

2021-05-27 11:03 UTC, ishwari-gaikwad2 commented on force-app/main/default/classes/ApplicationTriggerHandler.cls
> +            .Applications__r.size() >= 1
due to requirement of "opportunity will have only one applicant record "

2021-05-27 19:49 UTC, RemarioCRM requested changes

2021-05-27 19:49 UTC, RemarioCRM commented on force-app/main/default/triggers/ApplicationTrigger.trigger
> +  if (Trigger.isUpdate) {
ensure this trigger. has top level comments

2021-05-27 19:49 UTC, RemarioCRM commented on force-app/main/default/classes/ApplicationTriggerHandler.cls
> + * @last modified by  : Ishwari Gaikwad(Thinqloud)
Please. pull locally, review and merge then resolve conflicts. Repush afterwards

2021-05-28 13:36 UTC, closed without merging