Changes related to the RUB-261
crmmetry/JNGroupProject pull request #233
Opened 2021-05-19 12:59 UTC by ishwari-gaikwad2

2021-05-25 20:58 UTC, RemarioCRM requested changes

2021-05-25 20:59 UTC, RemarioCRM commented
Merge, fix changes and pull and resolve all conflicts

2021-05-27 11:02 UTC, ishwari-gaikwad2 commented on force-app/main/default/classes/ApplicationTriggerHandler.cls
> +    ];
we can add conditions on Group.DeveloperName for specific group

2021-05-27 19:48 UTC, RemarioCRM requested changes

2021-05-27 19:48 UTC, RemarioCRM commented on force-app/main/default/classes/CaseTriggerHandler.cls-meta.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
PLEASE pull locally resolve all conflicts then repush.

2021-05-28 13:36 UTC, closed without merging