Feature/rub 537
crmmetry/JNGroupProject pull request #235
Opened 2021-05-25 17:00 UTC by CRMTravis

2021-05-25 18:51 UTC, RemarioCRM requested changes

2021-05-25 18:51 UTC, RemarioCRM commented on force-app/main/default/aura/FinancialVerificationDetailsComponent/FinancialVerificationDetailsComponentHelper.js
> +    console.log("Primary Source of income: ", primarySourceOfIncome);
remove all console logs and dead code

2021-05-25 19:12 UTC, RemarioCRM requested changes

2021-05-25 19:12 UTC, RemarioCRM commented on force-app/main/default/classes/FinancialDetailsSelector.cls
>          Primary_Source_of_Income_VERIFIED_list__c,
ensure all queries have WITH SECURITY_ENFORCED

2021-05-25 19:24 UTC, CRMTravis commented on force-app/main/default/aura/FinancialVerificationDetailsComponent/FinancialVerificationDetailsComponentHelper.js
> +    console.log("Primary Source of income: ", primarySourceOfIncome);
Where is the dead code?

2021-05-25 19:41 UTC, RemarioCRM requested changes

2021-05-25 19:41 UTC, RemarioCRM commented on force-app/main/default/aura/FinancialVerificationDetailsComponent/FinancialVerificationDetailsComponentHelper.js
> +  getSelectedPrimarySourceOfIncomeValue: function (component) {
add jsdocs

2021-05-25 19:41 UTC, RemarioCRM commented on force-app/main/default/aura/MonthlyIncomeVerificationLineComponent/MonthlyIncomeVerificationLineComponent.cmp
> +  <aura:attribute name="childVerifiedDataMap" type="Map" default="{}" />
why is this needed, **childVerifiedDataMap** all of a sudden

2021-05-25 19:41 UTC, RemarioCRM commented on force-app/main/default/aura/MonthlyIncomeVerificationLineComponent/MonthlyIncomeVerificationLineComponent.cmp
> +    action="{!c.onChildVerifiedDataMapChange}"
whats the real difference between onVerifiedMonthlyIncomeMapChange vs onChildVerifiedDataMapChange

2021-05-25 19:41 UTC, RemarioCRM commented on force-app/main/default/aura/MonthlyIncomeVerificationLineComponent/MonthlyIncomeVerificationLineComponentController.js
> +  onChildVerifiedDataMapChange: function (component, event, helper) {
how do you prevent recursion?

2021-05-25 20:23 UTC, CRMTravis commented on force-app/main/default/aura/MonthlyIncomeVerificationLineComponent/MonthlyIncomeVerificationLineComponent.cmp
> +  <aura:attribute name="childVerifiedDataMap" type="Map" default="{}" />
All of a sudden?

2021-05-25 20:24 UTC, CRMTravis commented on force-app/main/default/aura/MonthlyIncomeVerificationLineComponent/MonthlyIncomeVerificationLineComponent.cmp
> +  <aura:attribute name="childVerifiedDataMap" type="Map" default="{}" />
Its been there from initial Implementation of the ticket which you removed.

2021-05-25 20:24 UTC, CRMTravis commented on force-app/main/default/aura/MonthlyIncomeVerificationLineComponent/MonthlyIncomeVerificationLineComponent.cmp
> +    action="{!c.onChildVerifiedDataMapChange}"
Semantics

2021-05-25 20:24 UTC, CRMTravis commented on force-app/main/default/aura/MonthlyIncomeVerificationLineComponent/MonthlyIncomeVerificationLineComponentController.js
> +  onChildVerifiedDataMapChange: function (component, event, helper) {
I made the Parent update a different map.

2021-05-25 20:46 UTC, RemarioCRM commented on force-app/main/default/aura/MonthlyIncomeVerificationLineComponent/MonthlyIncomeVerificationLineComponent.cmp
> +  <aura:attribute name="childVerifiedDataMap" type="Map" default="{}" />
childVerifiedDataMap is newly added?

2021-05-25 20:47 UTC, RemarioCRM commented on force-app/main/default/aura/MonthlyIncomeVerificationLineComponent/MonthlyIncomeVerificationLineComponent.cmp
> +    action="{!c.onChildVerifiedDataMapChange}"
it is not, most of your center around this change. I need to know why

2021-05-25 20:47 UTC, RemarioCRM commented on force-app/main/default/aura/MonthlyIncomeVerificationLineComponent/MonthlyIncomeVerificationLineComponentController.js
> +  onChildVerifiedDataMapChange: function (component, event, helper) {
which ones?

2021-05-26 13:28 UTC, CRMTravis commented on force-app/main/default/aura/MonthlyIncomeVerificationLineComponent/MonthlyIncomeVerificationLineComponentController.js
> +  onChildVerifiedDataMapChange: function (component, event, helper) {
I parsed the Financial Data into 3 maps Verified, Unverified and Totals. Unverified Map details are load upon initialisation into the child components. When change occurs on the child component belonging to the Verified Data map then the parent listens to it and makes the necessary calculations. the result of calculations are stored in a separate map for totals only which the child listens to and updates the appropriated totals. Parent child does not handle the or listen for totals changes so recursion is avoided.

2021-05-26 13:31 UTC, RemarioCRM commented on force-app/main/default/aura/MonthlyIncomeVerificationLineComponent/MonthlyIncomeVerificationLineComponentController.js
> +  onChildVerifiedDataMapChange: function (component, event, helper) {
neat trick

2021-05-26 13:36 UTC, CRMTravis commented on force-app/main/default/aura/MonthlyIncomeVerificationLineComponent/MonthlyIncomeVerificationLineComponentController.js
> +  onChildVerifiedDataMapChange: function (component, event, helper) {
Thanks

2021-05-26 15:57 UTC, RemarioCRM requested changes

2021-05-26 16:02 UTC, CRMTravis commented on force-app/main/default/staticresources/productDetailsGeneralFunctions.js
> +    if (calculationKey.includes("totalDebtConsolidatedVerified")) {
Forgot that we had a js file for constants tbh

2021-05-26 18:39 UTC, RemarioCRM approved these changes

2021-05-26 18:39 UTC, merged