Feature/rub 290
crmmetry/JNGroupProject pull request #238
Opened 2021-05-28 11:54 UTC by ishwari-gaikwad2

2021-05-28 13:32 UTC, RemarioCRM requested changes

2021-05-28 13:32 UTC, RemarioCRM commented on force-app/main/default/classes/CaseTriggerHandler_Test.cls
> +      //applicationList[0].Adjudication_Path_picklist__c = 'Closed';
remove dead code and all. system debug

2021-05-28 14:08 UTC, ishwari-gaikwad2 commented on force-app/main/default/classes/CaseTriggerHandler_Test.cls
> +      //applicationList[0].Adjudication_Path_picklist__c = 'Closed';
Removed.

2021-05-28 14:43 UTC, RemarioCRM requested changes

2021-06-02 15:04 UTC, RemarioCRM requested changes

2021-06-02 15:04 UTC, RemarioCRM commented on force-app/main/default/classes/ApplicationTriggerHandler.cls
> +            for (Case cases : applicationMap.get(newAppRecord.Id).cases__r) {
add null check to check applicationMap.get(newAppRecord.Id).cases__r

2021-06-02 15:04 UTC, RemarioCRM commented on force-app/main/default/classes/ApplicationTriggerHandler.cls
> +    for (Application__c newAppRecord : newRecords) {
@ishwari-gaikwad2 please add inline comments

2021-06-03 14:10 UTC, RemarioCRM requested changes

2021-06-03 14:10 UTC, RemarioCRM commented on force-app/main/default/classes/ApplicationTriggerHandler.cls
> +            for (Case cases : applicationMap.get(newAppRecord.Id).cases__r) {
please add

2021-06-03 14:10 UTC, RemarioCRM commented
@ishwari-gaikwad2 pull, make changes, and merge. then push again

2021-06-07 13:10 UTC, RemarioCRM requested changes

2021-06-07 13:10 UTC, RemarioCRM commented on force-app/main/default/classes/CaseTriggerHandler.cls
> +  public static void updateFlag(Set<Id> IdSet) {
add jsdocs, what is the reason behind this?

2021-06-07 13:10 UTC, RemarioCRM commented on force-app/main/default/classes/CaseTriggerHandler.cls
> +      if (
add inline comments stating purpose

2021-06-07 15:00 UTC, ishwari-gaikwad2 commented on force-app/main/default/classes/CaseTriggerHandler.cls
> +  public static void updateFlag(Set<Id> IdSet) {
We have used this future method as we were facing a problem with the process builder execution for chatter posts.
due to the order of execution in the salesforce, the field updated in the entitlement process did not execute the process builder or workflow rules, because of this issue we have updated that field in the future method

2021-06-07 15:09 UTC, RemarioCRM requested changes

2021-06-07 15:09 UTC, RemarioCRM commented on force-app/main/default/classes/CaseTriggerHandler.cls
>    public static void updateFlag(Set<Id> IdSet) {
rename updateFlag to updateCaseSLAEscalationFlag

2021-06-08 11:09 UTC, RemarioCRM requested changes

2021-06-08 11:09 UTC, RemarioCRM commented on force-app/main/default/triggers/CaseTrigger.trigger
> +      if (Trigger.isAfter) {
why change to isAfter

2021-06-08 14:31 UTC, ishwari-gaikwad2 commented on force-app/main/default/triggers/CaseTrigger.trigger
> +      if (Trigger.isAfter) {
this change was made 1-2 weeks before but, I think as you have back promoted changes my changes got overwritten and this change was not pushed to git hub

2021-06-09 19:20 UTC, merged