Selector for the Integration
crmmetry/JNGroupProject pull request #240
Opened 2021-06-02 13:13 UTC by ishwari-gaikwad2

2021-06-02 13:50 UTC, RemarioCRM requested changes

2021-06-02 13:50 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNQuerySelector.cls
> -  public static void getAccounts() {
Bulkify all the queries in this class

2021-06-02 18:05 UTC, RemarioCRM requested changes

2021-06-02 18:05 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNQuerySelector.cls
> +        Political_Exposure__pc,
i believe this field is wrong

2021-06-03 12:47 UTC, ishwari-gaikwad2 commented on force-app/main/default/classes/OneJNQuerySelector.cls
> +        Political_Exposure__pc,
which field?

2021-06-03 14:36 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNQuerySelector.cls
> +        Political_Exposure__pc,
Political_Exposure__pc

2021-06-03 14:41 UTC, RemarioCRM requested changes

2021-06-03 14:41 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNQuerySelector.cls
> +      FROM FinServ__Employment__c
add filter, current employment = TRUE

2021-06-07 16:38 UTC, RemarioCRM commented
@ishwari-gaikwad2 and @truptizende-Thinqloud merge into 523

2021-06-09 10:38 UTC, RemarioCRM commented
@ishwari-gaikwad2 and @truptizende-Thinqloud closing this pr. Changes are already in 529 branch.

2021-06-09 10:38 UTC, closed without merging