Feature/rub 515
crmmetry/JNGroupProject pull request #251
Opened 2021-06-10 12:37 UTC by ishwari-gaikwad2

2021-06-10 13:50 UTC, RemarioCRM requested changes

2021-06-10 13:50 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNEventFactory.cls
> +    system.debug('processGetManualEvent');
add proper descriptions to all methods, delete all system debugs. Use replay debugger @ishwari-gaikwad2 @truptizende-Thinqloud

2021-06-10 13:50 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNEventFactory.cls
> +    if (deserialiser.primaryApplicantRecord <> null) {
can we try performing one update instead of multiple updates?

2021-06-10 13:50 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNEventFactory.cls
> +    String EventType
all variables should be camel case

2021-06-10 14:31 UTC, RemarioCRM requested changes

2021-06-10 14:31 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNSerializer.cls
> +          opportunityProductRecord.Product_Family__c != 'JN Bank Credit Card'
Reuse or add to constants

2021-06-11 13:48 UTC, ishwari-gaikwad2 commented on force-app/main/default/classes/OneJNSerializer.cls
> +          opportunityProductRecord.Product_Family__c != 'JN Bank Credit Card'
all the above review changes are pushed.

2021-06-14 09:23 UTC, RemarioCRM requested changes

2021-06-14 09:23 UTC, RemarioCRM commented on force-app/main/default/classes/SerializerDecision.cls
> +      applicantJson.remove('monthlyExpensesNonCreditVerified');
why are we removing all these fields?

2021-06-14 15:50 UTC, RemarioCRM requested changes

2021-06-14 15:50 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNSerializerDecision.cls
> +      applicantJson.remove('MonthlyExpensesNonCreditVerified');
can we create a helper function that accepts an array of fields to remove instead?

2021-06-15 13:07 UTC, truptizende-Thinqloud commented on force-app/main/default/classes/OneJNSerializerDecision.cls
> +      applicantJson.remove('MonthlyExpensesNonCreditVerified');
added new method to remove list of fields passed and changes are pushed as well

2021-06-15 13:47 UTC, RemarioCRM requested changes

2021-06-15 13:47 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNQuerySelector.cls
> +  public static List<Application__c> getApplicationRecord(Id applicationId) {
add jsdocs

2021-06-15 13:48 UTC, RemarioCRM requested changes

2021-06-15 13:48 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNEventFactory.cls
> +  private static void processGetPreAssessmentEventResponse(
all process methods should have meaningful descriptions

2021-06-18 20:32 UTC, RemarioCRM requested changes

2021-06-18 20:32 UTC, RemarioCRM commented on force-app/main/default/classes/Constants.cls
> +  public static final String RETURN_MANUAL_DESICION_REJECT = 'JNGroup.OneJN.CreditInfo.Domain.Events.CreditCardManualDecisionEvent';
delete previous manual decisions constant.

2021-06-18 20:32 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNQuerySelector.cls
> +  public static Map<ID, FinServ__Employment__c> getEmploymentMap(
add jsdocs

2021-06-18 20:32 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNSerializer.cls
> -    Applicant__c ApplicantRecord,
please try to use camel with regular variables for example List<Applicant__c> ApplicantList, should List<Applicant__c> applicantList

2021-06-19 21:58 UTC, RemarioCRM requested changes

2021-06-23 01:35 UTC, merged