Feature/jn1 4198
crmmetry/JNGroupProject pull request #253
Opened 2021-06-11 20:13 UTC by CRMTravis

2021-06-11 20:21 UTC, RemarioCRM requested changes

2021-06-11 20:21 UTC, RemarioCRM commented on force-app/main/default/classes/SkillsBasedRouting.cls
> +    DateTime currentDateTime = System.now();
always. set specific static dates, using date.newInstance, currently your unit test becomes unpredictable every day

2021-06-11 20:34 UTC, CRMTravis commented on force-app/main/default/classes/SkillsBasedRouting.cls
> +    DateTime currentDateTime = System.now();
I don't understand why would I use static dates if the date is dynamic to whenever the class is instantiated.

2021-06-11 20:52 UTC, RemarioCRM commented on force-app/main/default/classes/SkillsBasedRouting.cls
> +    DateTime currentDateTime = System.now();
unit-testing is supposed to be predicable , if you use dynamic how will you debug the expectation in the near future

2021-06-11 20:56 UTC, CRMTravis commented on force-app/main/default/classes/SkillsBasedRouting.cls
> +    DateTime currentDateTime = System.now();
I use the addDays method for variability.

2021-06-11 21:11 UTC, RemarioCRM requested changes

2021-06-11 21:11 UTC, RemarioCRM commented on force-app/main/default/classes/TestSkillsBasedRouting.cls
> +    travisAnnottoBaySkill.EffectiveStartDate = System.now().addDays(-1);
modify the test setup to be leaner.

2021-06-15 16:22 UTC, RemarioCRM requested changes

2021-06-15 16:22 UTC, RemarioCRM commented on force-app/main/default/classes/SkillsBasedRouting.cls
> +  public static void routeUsingSkillsTier2(
add jsdocs

2021-06-15 16:22 UTC, RemarioCRM commented on force-app/main/default/classes/SkillsBasedRouting.cls
> +  public static void StartRoutingUsingTier2(
add jsdocs

2021-06-15 16:22 UTC, RemarioCRM commented on force-app/main/default/classes/SkillsBasedRouting.cls
> -            SKill.Id IN :mappedLocationSkills.keySet()
add some inline comments to explain what's going on with this query.

2021-06-16 16:14 UTC, RemarioCRM requested changes

2021-06-16 16:14 UTC, RemarioCRM commented on force-app/main/default/classes/SkillsBasedRouting.cls
> -            SKill.Id IN :mappedLocationSkills.keySet()
all methods in the skill-based class should have a method description

2021-06-16 16:14 UTC, RemarioCRM commented on force-app/main/default/classes/TestSkillsBasedRouting.cls
>          SELECT Id
use this method instead Util.getQueueId

2021-06-16 16:14 UTC, RemarioCRM commented on force-app/main/default/classes/TestSkillsBasedRouting.cls
>        insert salesTeamMembers;
use CreateGroupMember from testdata factory

2021-06-17 13:52 UTC, RemarioCRM approved these changes

2021-06-17 14:07 UTC, merged