Feature/jn1 1494 renewed
crmmetry/JNGroupProject pull request #260
Opened 2021-06-23 19:50 UTC by CRMTravis

2021-06-26 22:06 UTC, RemarioCRM requested changes

2021-06-26 22:06 UTC, RemarioCRM commented on force-app/main/default/classes/NoContactMadeNotifierQueueable.cls
> +   *Logic to calculate time when lead is reassigned, hence max allowableTime is 8
is it always 8, if not modify jsdocs

2021-06-26 22:06 UTC, RemarioCRM commented on force-app/main/default/classes/NoContactMadeNotifierQueueable.cls
> +          !leadRecord.Lead_Reassigned_flag__c &&
what is the logic for Lead_Reassigned_flag__c?

2021-06-26 22:06 UTC, RemarioCRM commented on force-app/main/default/classes/NoContactMadeNotifierQueueable.cls
> +        Last_Contact_Made__c
please add a necessary filter, this will return all leads. Think about it, which lead records should be returned?

2021-06-26 22:07 UTC, RemarioCRM commented
@CRMTravis let's say, your logic runs perfectly, how will the user be notified after all the processing is completed?

2021-06-28 12:14 UTC, CRMTravis commented on force-app/main/default/classes/NoContactMadeNotifierQueueable.cls
> +          !leadRecord.Lead_Reassigned_flag__c &&
Identifies a lead that has been reassigned.

2021-06-28 12:15 UTC, CRMTravis commented on force-app/main/default/classes/NoContactMadeNotifierQueueable.cls
> +   *Logic to calculate time when lead is reassigned, hence max allowableTime is 8
Yes

2021-06-28 13:19 UTC, RemarioCRM requested changes

2021-06-28 13:19 UTC, RemarioCRM commented on force-app/main/default/classes/NoContactMadeNotifierQueueable.cls
>        WITH SECURITY_ENFORCED
this query can potentially return a lot of records. Think, what leads am I really interested in. What filter can exclude already processed records?

2021-07-12 21:09 UTC, closed without merging