Feature/rub 515
crmmetry/JNGroupProject pull request #261
Opened 2021-06-28 15:15 UTC by ishwari-gaikwad2

Test class for RUb-449

2021-06-28 23:18 UTC, RemarioCRM requested changes

2021-06-28 23:18 UTC, RemarioCRM commented on force-app/main/default/classes/TestONeJNEventSubmissionHandler.cls
> +  public static void handleCreditCardFinalAssessmentEvent() {
each test method. must have comments

2021-06-28 23:18 UTC, RemarioCRM commented on force-app/main/default/classes/TestONeJNEventSubmissionHandler.cls
> +    system.assertEquals('Referred', opp.Final_Assessment_Decision_list__c);
use constants forall texts

2021-06-28 23:18 UTC, RemarioCRM commented on force-app/main/default/classes/TestONeJNEventSubmissionHandler.cls
> +    system.assertEquals('Referred', opp.Final_Assessment_Decision_list__c);
picklist values

2021-06-29 14:43 UTC, truptizende-Thinqloud commented on force-app/main/default/classes/TestONeJNEventSubmissionHandler.cls
> +    system.assertEquals('Referred', opp.Final_Assessment_Decision_list__c);
Used constants to all texts.

2021-06-30 13:27 UTC, RemarioCRM requested changes

2021-06-30 13:27 UTC, RemarioCRM commented on force-app/main/default/classes/TestONeJNEventSubmissionHandler.cls
> +      OPPORTUNITYSTRING
This is failing, please rerun, report progress. then push again

2021-06-30 14:16 UTC, ishwari-gaikwad2 commented on force-app/main/default/classes/TestONeJNEventSubmissionHandler.cls
> +      OPPORTUNITYSTRING
the test class is not failing in dev box 4.

2021-06-30 14:52 UTC, RemarioCRM requested changes

2021-06-30 14:52 UTC, RemarioCRM commented on force-app/main/default/classes/TestONeJNEventSubmissionHandler.cls
> +      OPPORTUNITYSTRING
OPPORTUNITYSTRING should be Constants. OPPORTUNITYSTRING, so yes its an error.

2021-07-01 10:50 UTC, RemarioCRM approved these changes

2021-07-01 10:50 UTC, merged