RUB-138 related changes
crmmetry/JNGroupProject pull request #263
Opened 2021-07-01 14:45 UTC by ishwari-gaikwad2

2021-07-01 18:43 UTC, RemarioCRM requested changes

2021-07-01 18:43 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNEventService.cls
> +  public static List<Document_Instruction__c> getDocumentInstructionInstance(
add jsdocs

2021-07-02 12:32 UTC, RemarioCRM requested changes

2021-07-02 12:32 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNDeserializer.cls
>    public class DocumentRequirementsWrapper {
delete dead code

2021-07-02 12:32 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNSerializer.cls
> +        /*
remove dead code

2021-07-02 12:32 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNSerializer.cls
> +        if( applicationRecord.Adjudication_Decision_picklist__c ==Constants.MANUAL_APPROVE
what is this change for?

2021-07-02 12:36 UTC, ishwari-gaikwad2 commented on force-app/main/default/classes/OneJNSerializer.cls
> +        if( applicationRecord.Adjudication_Decision_picklist__c ==Constants.MANUAL_APPROVE
This is for RUB-656 picklist values related changes

2021-07-02 13:53 UTC, RemarioCRM requested changes

2021-07-02 13:53 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNEventService.cls
> +        insert documentChecklistItem;
SobjectDecision class for security.

2021-07-02 14:30 UTC, ishwari-gaikwad2 commented on force-app/main/default/classes/OneJNEventService.cls
> +        insert documentChecklistItem;
@RemarioCRM - as we are creating document checklist items from the automated process. when i add sObjectDecision class it gives an error that "No access to entity: DocumentChecklistItem". so i tried to assign document checklist item permission set to that user but not able to do that.. what can be done in this case?

2021-07-02 14:35 UTC, ishwari-gaikwad2 commented on force-app/main/default/classes/OneJNEventService.cls
> +        insert documentChecklistItem;
@RemarioCRM - when i add the sObjectDecision for insertion of the Document checklist item i am getting this error: "No access to entity: DocumentChecklistItem". I think this is due to the record is getting created from the Automated process.
so i tried assigning the "DocumentChecklistItem" permission set to that user but unable to do that.
Please suggest.

2021-07-02 15:27 UTC, RemarioCRM commented on force-app/main/default/classes/OneJNEventService.cls
> +        insert documentChecklistItem;
@ishwari-gaikwad2 the class is invoked from a queueable from a flow as described previously, so it's not an automated process.

2021-07-05 12:22 UTC, RemarioCRM requested changes

2021-07-05 15:05 UTC, RemarioCRM approved these changes

2021-07-05 15:06 UTC, merged