Feature/rub 138 v1
crmmetry/JNGroupProject pull request #266
Opened 2021-07-07 15:20 UTC by ishwari-gaikwad2

2021-07-08 13:33 UTC, RemarioCRM requested changes

2021-07-08 13:33 UTC, RemarioCRM commented on force-app/main/default/classes/Constants.cls
> + * @last modified by  : Trupti Zende (Thinqloud)
i. thought Trupti Zende is no longer with THinqcloud?

2021-07-09 17:03 UTC, ishwari-gaikwad2 commented on force-app/main/default/classes/Constants.cls
> + * @last modified by  : Trupti Zende (Thinqloud)
Yes.

2021-07-12 15:07 UTC, RemarioCRM approved these changes

2021-07-12 15:07 UTC, merged